# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('UserManage', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(default=uuid.uuid1, on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManage.User', verbose_name='user'),
        ),
    ]
