# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('store_path', models.CharField(default='', max_length=255)),
                ('url_path', models.CharField(default='', max_length=255)),
                ('num_views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(default='', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
